### PR TITLE
Fix plugin name

### PR DESCRIPTION
**Pull request by shoonia**
Copy and paste of config snippet doesn't work )

### CODE REVIEW

**Comment by dosentmatter** [comment]
Hey @shoonia, thanks for the PR. What kind of error are you getting? Babel has plugin/preset shorthand names:

https://babeljs.io/docs/en/plugins/#plugin-shorthand
https://babeljs.io/docs/en/presets#preset-shorthand

If the name of the package is prefixed with babel-plugin-, you can use a shorthand:

```js
{
  "plugins": [
    "myPlugin",
    "babel-plugin-myPlugin" // equivalent
  ]
}
```

```js
{
  "plugins": [
    "@org/babel-plugin-name",
    "@org/name" // equivalent
  ]
}
```

What they don't document is that `@babel/plugin-transform-typescript` is also equivalent to `@babel/transform-typescript`, even though it doesn't begin with `babel-plugin-` eg. `@babel/babel-plugin-transform-typescript`. Though I think that is a special case for plugins within the `@babel` organization since it already begins with `@babel/`.

---

Anyway, you can see other repos use the shorthand eg. [microsoft / TypeScript-Babel-Starter](https://github.com/microsoft/TypeScript-Babel-Starter/blob/master/.babelrc):

```json
{
  "presets": ["@babel/env", "@babel/typescript"],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

Notice the shorthands for `@babel/preset-env`, `@babel/preset-typescript`, `@babel/plugin-proposal-class-properties`, and `@babel/plugin-proposal-object-rest-spread`.

I think the shorthand is there to avoid redundancy since it's already scoped under a `plugins` or `presets` property. But `babel-plugin-` is still in the package name since it's in the scope of npm packages, which can be anything.

**Review by dosentmatter — COMMENTED** [review]
Hey @shoonia, thanks for the PR. What kind of error are you getting? Babel has plugin/preset shorthand names:

https://babeljs.io/docs/en/plugins/#plugin-shorthand
https://babeljs.io/docs/en/presets#preset-shorthand

If the name of the package is prefixed with babel-plugin-, you can use a shorthand:

```js
{
  "plugins": [
    "myPlugin",
    "babel-plugin-myPlugin" // equivalent
  ]
}
```

```js
{
  "plugins": [
    "@org/babel-plugin-name",
    "@org/name" // equivalent
  ]
}
```

What they don't document is that `@babel/plugin-transform-typescript` is also equivalent to `@babel/transform-typescript`, even though it doesn't begin with `babel-plugin-` eg. `@babel/babel-plugin-transform-typescript`. Though I think that is a special case for plugins within the `@babel` organization since it already begins with `@babel/`.

---

Anyway, you can see other repos use the shorthand eg. [microsoft / TypeScript-Babel-Starter](https://github.com/microsoft/TypeScript-Babel-Starter/blob/master/.babelrc):

```json
{
  "presets": ["@babel/env", "@babel/typescript"],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

Notice the shorthands for `@babel/preset-env`, `@babel/preset-typescript`, `@babel/plugin-proposal-class-properties`, and `@babel/plugin-proposal-object-rest-spread`.

I think the shorthand is there to avoid redundancy since it's already scoped under a `plugins` or `presets` property. But `babel-plugin-` is still in the package name since it's in the scope of npm packages, which can be anything.

**Comment by shoonia** [comment]
Hi, @dosentmatter !

I'm sorry, I wrote not clear about the issue. I mean to fix a plugin name in documentation ("@babel/plugin-transform-typescript").

```diff
{
-  "plugins": ["const-enum", "@babel/transform-typescript"]
+  "plugins": ["const-enum", "@babel/plugin-transform-typescript"]
}

I copy and paste the config snippet from the documentation, and it doesn't work.
```

**Comment by dosentmatter** [comment]
> Hi, @dosentmatter !
> 
> I'm sorry, I wrote not clear about the issue. I mean to fix a plugin name in documentation ("@babel/plugin-transform-typescript").
> 
> 
> {
> -  "plugins": ["const-enum", "@babel/transform-typescript"]
> +  "plugins": ["const-enum", "@babel/plugin-transform-typescript"]
> }
> 
> I copy and paste the config snippet from the documentation, and it doesn't work.

Hey @shoonia, I understand what you mean. As I posted in the previous comment, the configuration in the README should work. It is partially documented in the babel docs and used in the TypeScript Babel Starter repo. It also works for me.

If you are having issues please provide me a repo with a minimal reproduction and let me know the error you are getting because I am not able to reproduce any problems.

**Pull request closed without merging**
